const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const {stripTypeScriptTypes}=require('node:module');
const compiled=stripTypeScriptTypes(fs.readFileSync(require('node:path').join(__dirname,'../src/lib/formDraft.ts'),'utf8')).replace(/export /g,'')+'\nObject.assign(exports,{readFormDraft,writeFormDraft,removeFormDraft,formContinuation,loginForForm,registrationForForm});';
function setup(){const storage=new Map();const context={exports:{},sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}};vm.runInNewContext(compiled,context);return {api:context.exports,context,storage}}
test('departure and return preserve independent unsent data across form remount',()=>{const s=setup();s.api.writeFormDraft('departure',{name:'PPIU Test',items:[{code:'DOC01',notes:'Bukti test'}]});s.api.writeFormDraft('return',{name:'PPIU Return'});assert.equal(s.api.readFormDraft('departure',()=>({})).items[0].notes,'Bukti test');assert.equal(s.api.readFormDraft('return',()=>({})).name,'PPIU Return');s.api.removeFormDraft('departure');assert.equal(s.api.readFormDraft('departure',()=>({name:'Blank'})).name,'Blank');assert.equal(s.api.readFormDraft('return',()=>({})).name,'PPIU Return')});
test('corrupt, expired and invalid drafts do not block form entry',()=>{for(const raw of ['bad',JSON.stringify({version:1,savedAt:Date.now()-86400001,value:{name:'Old'}}),JSON.stringify({version:1,savedAt:Date.now(),value:{bad:'Schema'}})]){const s=setup();s.storage.set('kemenhaj-form-draft-v1:test',raw);assert.equal(s.api.readFormDraft('test',()=>({name:'Blank'}),v=>typeof v.name==='string').name,'Blank')}});
test('blocked browser storage is reported without losing in-memory editing',()=>{const s=setup();s.context.sessionStorage.setItem=()=>{throw Error('Quota')};assert.equal(s.api.writeFormDraft('test',{name:'Test'}),false);s.context.sessionStorage.getItem=()=>{throw Error('Disabled')};assert.equal(s.api.readFormDraft('test',()=>({name:'Blank'})).name,'Blank')});
test('only approved form paths resume and role permissions remain intact',()=>{const s=setup();const departure='/layanan/pelaporan-travel-umrah/pengajuan',kloter='/layanan/pemulangan-haji-reguler/pengajuan';assert.equal(s.api.formContinuation(departure,'travel'),departure);assert.equal(s.api.formContinuation(kloter,'staff'),kloter);assert.equal(s.api.formContinuation(kloter,'travel'),null);assert.equal(s.api.formContinuation(departure,'pengguna'),null);for(const path of ['__proto__','constructor','https://evil.test','//evil.test','/admin/users',departure+'?url=evil',null])assert.equal(s.api.formContinuation(path,'admin'),null);assert.equal(s.api.loginForForm(departure),'/masuk?lanjut='+encodeURIComponent(departure));assert.equal(s.api.registrationForForm(departure),'/daftar-travel?lanjut='+encodeURIComponent(departure))});
