import { useEffect, useState } from 'react';
import { api } from '../lib/api';

type Company={id:string;name:string;nib:string|null;office_address:string|null};
type Account={id:string;name:string;email:string;role:string;company_id:string|null};
type Application={id:string;reference:string;company_name:string;status:string;review_notes:string|null;created_at:string};
const roles=['staff','travel','konsultan','pengawas','pengguna'];

export function AccountsPage(){
  const [companies,setCompanies]=useState<Company[]>([]);const [users,setUsers]=useState<Account[]>([]);
  const [company,setCompany]=useState({name:'',nib:'',office_address:''});
  const [account,setAccount]=useState({name:'',email:'',password:'',role:'staff',company_id:''});
  const [error,setError]=useState('');const [notice,setNotice]=useState('');
  async function load(){try{const [c,u]=await Promise.all([api<{companies:Company[]}>('/users/companies'),api<{users:Account[]}>('/users')]);setCompanies(c.companies);setUsers(u.users)}catch(e){setError(e instanceof Error?e.message:'Gagal memuat akun.')}}
  useEffect(()=>{void load()},[]);
  async function addCompany(e:React.FormEvent){e.preventDefault();setError('');setNotice('');try{await api('/users/companies',{method:'POST',body:company});setCompany({name:'',nib:'',office_address:''});setNotice('Perusahaan ditambahkan.');await load()}catch(err){setError(err instanceof Error?err.message:'Gagal menyimpan perusahaan.')}}
  async function addAccount(e:React.FormEvent){e.preventDefault();setError('');setNotice('');try{await api('/users',{method:'POST',body:account});setAccount({name:'',email:'',password:'',role:'staff',company_id:''});setNotice('Akun dibuat. Sampaikan akses awal melalui kanal resmi.');await load()}catch(err){setError(err instanceof Error?err.message:'Gagal membuat akun.')}}
  async function change(account:Account,role:string,company_id:string|null){setError('');try{await api(`/users/${account.id}/role`,{method:'PATCH',body:{role,company_id}});await load()}catch(err){setError(err instanceof Error?err.message:'Gagal mengubah akses.')}}
  return <div className="dash-page"><div className="dash-page-head"><div><h1>Akun dan perusahaan travel</h1><p>Administrator membuat akun staf dan mengikat akun travel ke satu perusahaan.</p></div></div>{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="dash-panel"><h2>Tambah perusahaan</h2><form onSubmit={addCompany} style={{display:'grid',gap:10,maxWidth:580}}><label>Nama perusahaan<input required value={company.name} onChange={e=>setCompany({...company,name:e.target.value})}/></label><label>NIB<input value={company.nib} onChange={e=>setCompany({...company,nib:e.target.value})}/></label><label>Alamat kantor<input value={company.office_address} onChange={e=>setCompany({...company,office_address:e.target.value})}/></label><button className="btn primary">Simpan perusahaan</button></form><p>{companies.length} perusahaan terdaftar.</p></div><div className="dash-panel" style={{marginTop:16}}><h2>Buat akun</h2><form onSubmit={addAccount} style={{display:'grid',gap:10,maxWidth:580}}><label>Nama<input required value={account.name} onChange={e=>setAccount({...account,name:e.target.value})}/></label><label>Email<input required type="email" value={account.email} onChange={e=>setAccount({...account,email:e.target.value})}/></label><label>Sandi awal (minimal 12 karakter)<input required minLength={12} type="password" autoComplete="new-password" value={account.password} onChange={e=>setAccount({...account,password:e.target.value})}/></label><label>Peran<select value={account.role} onChange={e=>setAccount({...account,role:e.target.value,company_id:''})}>{roles.map(r=><option key={r} value={r}>{r}</option>)}</select></label>{account.role==='travel'&&<label>Perusahaan<select required value={account.company_id} onChange={e=>setAccount({...account,company_id:e.target.value})}><option value="">Pilih perusahaan</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<button className="btn primary">Buat akun</button></form></div><div className="dash-panel" style={{marginTop:16}}><h2>Daftar akun</h2>{users.map(u=><div key={u.id} style={{padding:'12px 0',borderBottom:'1px solid #ddd'}}><strong>{u.name}</strong> · {u.email} · {u.role}{u.company_id&&` · ${companies.find(c=>c.id===u.company_id)?.name||'Perusahaan tidak ditemukan'}`}<div>{u.role!=='admin'&&<><select aria-label={`Peran ${u.name}`} value={u.role} onChange={e=>void change(u,e.target.value,e.target.value==='travel'?u.company_id||companies[0]?.id||null:null)}>{roles.map(r=><option key={r} value={r}>{r}</option>)}</select>{u.role==='travel'&&<select aria-label={`Perusahaan ${u.name}`} value={u.company_id||''} onChange={e=>void change(u,'travel',e.target.value)}><option value="">Pilih perusahaan</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}</>}</div></div>)}</div></div>;
}

export function TravelPage(){
  const [items,setItems]=useState<Application[]>([]);const [form,setForm]=useState({applicant_name:'',applicant_phone:'',office_address:'',description:''});
  const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
  async function load(){try{const d=await api<{applications:Application[]}>('/operations/ppiu/my');setItems(d.applications)}catch(e){setError(e instanceof Error?e.message:'Gagal memuat pengajuan.')}}
  useEffect(()=>{void load()},[]);
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{const d=await api<{application:Application}>('/operations/ppiu/my',{method:'POST',body:form});setNotice(`Pengajuan ${d.application.reference} diterima.`);setForm({applicant_name:'',applicant_phone:'',office_address:'',description:''});await load()}catch(err){setError(err instanceof Error?err.message:'Gagal mengirim.')}finally{setBusy(false)}}
  return <div className="dash-page"><div className="dash-page-head"><div><h1>Pengajuan perusahaan travel</h1><p>Hanya pengajuan yang terkait dengan perusahaan akun ini yang ditampilkan. Pengajuan awal bukan izin terbit.</p></div></div>{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="dash-panel"><h2>Pengajuan awal PPIU</h2><form onSubmit={submit} style={{display:'grid',gap:12,maxWidth:640}}><label>Nama penanggung jawab<input required value={form.applicant_name} onChange={e=>setForm({...form,applicant_name:e.target.value})}/></label><label>Telepon<input required value={form.applicant_phone} onChange={e=>setForm({...form,applicant_phone:e.target.value})}/></label><label>Alamat kantor (bila belum tercatat)<input value={form.office_address} onChange={e=>setForm({...form,office_address:e.target.value})}/></label><label>Uraian pengajuan<textarea required rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="btn primary" disabled={busy}>{busy?'Mengirim…':'Kirim pengajuan'}</button></form></div><div className="dash-panel" style={{marginTop:16}}><h2>Riwayat perusahaan</h2>{!items.length&&<p>Belum ada pengajuan yang terkait dengan akun perusahaan ini.</p>}{items.map(item=><article key={item.id} style={{padding:'12px 0',borderBottom:'1px solid #ddd'}}><strong>{item.reference}</strong> · {item.company_name} · {item.status}{item.review_notes&&<p>Catatan petugas: {item.review_notes}</p>}</article>)}</div></div>;
}
