import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '../lib/api';
import { useAuth } from '../hooks/useAuth';
import { useFormDraft } from '../hooks/useFormDraft';
import { loginForForm } from '../lib/formDraft';

type Application = { id:string; reference:string; company_name:string; applicant_name:string; applicant_email:string; status:string; review_notes?:string; created_at:string };
type Report = { id:string; reference:string; kloter_code:string; regions:string[]; flight_number?:string; total_people?:number; male_count?:number; female_count?:number; status:string; created_at:string; [key:string]:unknown };
const reportLabels: Record<string,string> = {draft:'Draf', submitted:'Dikirim', reviewed:'Ditinjau', returned:'Perlu perbaikan'};
const applicationLabels: Record<string,string> = {submitted:'Dikirim',in_review:'Diperiksa',needs_revision:'Perlu perbaikan',forwarded:'Diteruskan ke proses resmi',closed:'Ditutup'};
const localDateTime = (value:unknown) => {
  if (!value) return '';
  const date = new Date(String(value));
  if (Number.isNaN(date.getTime())) return '';
  const pad = (n:number) => String(n).padStart(2,'0');
  return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;
};

export function PpiuForm(){
  const [form,setForm]=useState({applicant_name:'',applicant_email:'',applicant_phone:'',company_name:'',nib:'',office_address:'',description:''});
  const [reference,setReference]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const fields: [keyof typeof form,string,boolean][] = [['applicant_name','Nama penanggung jawab',true],['applicant_email','Email aktif',true],['applicant_phone','Nomor telepon / WhatsApp',true],['company_name','Nama badan usaha PPIU',true],['nib','NIB (jika tersedia)',false],['office_address','Alamat kantor',true],['description','Uraian pengajuan dan dokumen yang tersedia',true]];
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api<{application:{reference:string}}>('/operations/ppiu/public',{method:'POST',body:form});setReference(result.application.reference)}catch(err){setError(err instanceof Error?err.message:'Gagal mengirim.')}finally{setBusy(false)}}
  return <main className="login-section"><div className="login-card" style={{maxWidth:680}}><h1>Pengajuan awal izin PPIU</h1><p>Petugas Riau memeriksa informasi awal dan mengarahkan proses perizinan nasional. Pengiriman formulir ini belum menerbitkan izin.</p>{reference?<div role="status"><h2>Pengajuan diterima</h2><p>Simpan nomor referensi <strong>{reference}</strong>.</p><Link className="btn primary full" to={`/cek-izin-ppiu?ref=${encodeURIComponent(reference)}`}>Lihat status</Link></div>:<form onSubmit={submit}>{fields.map(([key,label,required])=><label key={key}>{label}{key==='description'?<textarea value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} required={required} rows={4} style={{width:'100%',padding:12}}/>:<input type={key==='applicant_email'?'email':'text'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} required={required}/>}</label>)}{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn primary full" disabled={busy}>{busy?'Mengirim…':'Kirim pengajuan awal'}</button></form>}<p><Link to="/layanan/perizinan-ppiu">Kembali ke informasi layanan</Link></p></div></main>;
}

export function PpiuTrack(){
  const [ref,setRef]=useState(new URLSearchParams(window.location.search).get('ref')||'');const [email,setEmail]=useState('');const [item,setItem]=useState<Application|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setItem(null);try{const result=await api<{application:Application}>(`/operations/ppiu/track?reference=${encodeURIComponent(ref.trim())}&email=${encodeURIComponent(email.trim())}`);setItem(result.application)}catch(err){setError(err instanceof Error?err.message:'Gagal memeriksa status.')}finally{setBusy(false)}}
  return <main className="login-section"><div className="login-card"><h1>Status pengajuan PPIU</h1><p>Masukkan referensi dan email yang dipakai saat pengajuan.</p><form onSubmit={submit}><label>Nomor referensi<input required value={ref} onChange={e=>setRef(e.target.value)}/></label><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn primary full" disabled={busy}>{busy?'Memeriksa…':'Cek status'}</button></form>{item&&<section role="status"><h2>{item.company_name}</h2><p>{item.reference} · {applicationLabels[item.status]||item.status}</p>{item.review_notes&&<p>Catatan petugas: {item.review_notes}</p>}</section>}</div></main>;
}

export function OperationsDashboard({base,kind}:{base:string;kind:'returns'|'ppiu'}){
  const [reports,setReports]=useState<Report[]>([]);const [applications,setApplications]=useState<Application[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function load(){setBusy(true);setError('');try{if(kind==='returns'){const d=await api<{reports:Report[]}>('/operations/returns');setReports(d.reports)}else{const d=await api<{applications:Application[]}>('/operations/ppiu');setApplications(d.applications)}}catch(err){setError(err instanceof Error?err.message:'Gagal memuat data.')}finally{setBusy(false)}}
  useEffect(()=>{void load()},[kind]);
  async function changeApplication(item:Application,status:string){try{await api(`/operations/ppiu/${item.id}`,{method:'PATCH',body:{status,review_notes:item.review_notes||''}});await load()}catch(err){setError(err instanceof Error?err.message:'Gagal menyimpan.') }}
  return <div className="dash-page managed-forms"><div className="dash-page-head"><div><h1>{kind==='returns'?'Laporan Kepulangan Kloter':'Pengajuan awal PPIU'}</h1><p>{kind==='returns'?'Register operasional kloter. Rincian kesehatan hanya untuk petugas berwenang.':'Pemeriksaan awal administrasi; penerbitan izin mengikuti sistem nasional.'}</p></div>{kind==='returns'&&<Link className="btn primary" to={`${base}/laporan-kloter/baru`}>Buat laporan</Link>}</div>{error&&<p className="form-error" role="alert">{error}</p>}{busy&&<p>Memuat…</p>}{kind==='returns'?<div className="dash-panel">{!busy&&!error&&!reports.length&&<p>Belum ada laporan kloter.</p>}{reports.map(r=><p key={r.id}><Link to={`${base}/laporan-kloter/${r.id}`}><strong>{r.kloter_code}</strong> · {r.reference}</Link> · {reportLabels[r.status]||r.status} · {r.total_people??'—'} orang</p>)}</div>:<div className="dash-panel">{!busy&&!error&&!applications.length&&<p>Belum ada pengajuan PPIU.</p>}{applications.map(item=><article key={item.id} style={{padding:'16px 0',borderBottom:'1px solid #ddd'}}><strong>{item.company_name}</strong> · {item.reference}<p>{item.applicant_name} · {item.applicant_email} · {applicationLabels[item.status]||item.status}</p><label>Catatan petugas<input value={item.review_notes||''} onChange={e=>setApplications(applications.map(a=>a.id===item.id?{...a,review_notes:e.target.value}:a))}/></label><select aria-label="Ubah status" value={item.status} onChange={e=>void changeApplication(item,e.target.value)}>{Object.entries(applicationLabels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select> <button className="btn light" type="button" onClick={()=>void changeApplication(item,item.status)}>Simpan catatan</button></article>)}</div>}</div>;
}

export function ReturnReportEditor({base='/staff',publicEntry=false}:{base?:string;publicEntry?:boolean}){
  const {id}=useParams();const nav=useNavigate();const {isAuth,user}=useAuth();const isNew=publicEntry||id==='baru';const allowed=isAuth&&Boolean(user&&['admin','staff'].includes(user.role));const targetBase=user?.role==='admin'?'/admin':base;const {value:report,setValue:setReport,persist,clear,storageAvailable}=useFormDraft<Partial<Report>>('return-kloter',publicEntry,()=>({kloter_code:'',regions:[],status:'draft'}),v=>Boolean(v&&typeof v==='object'&&typeof (v as Partial<Report>).kloter_code==='string'&&Array.isArray((v as Partial<Report>).regions)));const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  useEffect(()=>{if(isNew)return;api<{report:Report}>(`/operations/returns/${id}`).then(d=>setReport(d.report)).catch(err=>setError(err instanceof Error?err.message:'Gagal memuat laporan.'))},[id,isNew]);
  const fields:[string,string,string][]=[['kloter_code','Kode kloter','text'],['regions','Kabupaten/kota (pisahkan koma)','text'],['wave','Gelombang','number'],['flight_number','Nomor penerbangan','text'],['origin','Bandara asal','text'],['destination','Bandara tujuan','text'],['departure_at','Perkiraan berangkat (waktu lokal)','datetime-local'],['arrival_at','Perkiraan tiba (waktu lokal)','datetime-local'],['total_people','Total jemaah dan petugas','number'],['male_count','Laki-laki','number'],['female_count','Perempuan','number'],['risk_high','Risti berat','number'],['risk_medium','Risti sedang','number'],['risk_low','Risti ringan','number'],['non_risk','Non risti','number'],['under_60','Usia di bawah 60','number'],['age_60_plus','Usia 60 ke atas','number'],['wheelchair_count','Membutuhkan kursi roda','number'],['hospitalized_count','Masih dirawat','number'],['death_count','Meninggal','number']];
  const groups:{key:string;title:string;labels:string[]}[]=[
    {key:'staff',title:'Petugas kloter',labels:['Jabatan','Nama','Kontak']},
    {key:'accommodation',title:'Penempatan hotel',labels:['Kota','Sektor','Hotel']},
    {key:'disease_counts',title:'Penyakit terbanyak (agregat)',labels:['Kode / penyakit','Jumlah']},
    {key:'sensitive_cases',title:'Kasus khusus (rahasia petugas)',labels:['Jenis kasus','Nama jemaah','Nomor porsi','Usia','Diagnosis','Asal kloter','Catatan']},
  ];
  const editable=isNew||['draft','returned'].includes(report.status||'');
  function items(key:string):Record<string,string>[]{return Array.isArray(report[key])?report[key] as Record<string,string>[]:[]}
  function setItem(key:string,index:number,field:string,value:string){setReport(old=>({...old,[key]:items(key).map((item,i)=>i===index?{...item,[field]:value}:item)}))}
  function addItem(key:string){setReport(old=>({...old,[key]:[...items(key),{}]}))}
  function removeItem(key:string,index:number){setReport(old=>({...old,[key]:items(key).filter((_,i)=>i!==index)}))}
  function setField(key:string,value:string,type:string){setReport(old=>({...old,[key]:key==='regions'?value.split(',').map(s=>s.trim()).filter(Boolean):type==='number'?(value===''?null:Number(value)):type==='datetime-local'?(value?new Date(value).toISOString():null):value}))}
  async function save(e:React.FormEvent){e.preventDefault();if(!isAuth){if(persist())nav(loginForForm(location.pathname));else setError('Penyimpanan sementara browser tidak tersedia. Aktifkan penyimpanan browser sebelum login agar isian tidak hilang.');return}if(!allowed){setError('Laporan kloter hanya dapat dikirim dengan akun Admin atau Staf. Isian tetap tersimpan.');return}setBusy(true);setError('');try{const body={...report};delete body.id;delete body.reference;delete body.status;delete body.created_at;delete body.created_by;delete body.updated_at;delete body.submitted_at;delete body.reviewed_at;delete body.reviewed_by;const d=await api<{report:Report}>(isNew?'/operations/returns':`/operations/returns/${id}`,{method:isNew?'POST':'PATCH',body});clear();nav(`${targetBase}/laporan-kloter/${d.report.id}`,{replace:true})}catch(err){setError(err instanceof Error?err.message:'Gagal menyimpan.')}finally{setBusy(false)}}
  async function changeStatus(status:string){setBusy(true);setError('');try{const d=await api<{report:Report}>(`/operations/returns/${id}/status`,{method:'PATCH',body:{status}});setReport(d.report)}catch(err){setError(err instanceof Error?err.message:'Gagal mengubah status.')}finally{setBusy(false)}}
  return <div className="dash-page managed-forms"><div className="dash-page-head"><div><h1>{isNew?'Buat laporan kloter':`Laporan ${report.kloter_code||''}`}</h1><p>{report.reference||'Draf baru'} · {reportLabels[report.status||'draft']||report.status}</p></div><Link to={publicEntry?'/layanan?category=Pelaporan':`${base}/laporan-kloter`}>Kembali ke {publicEntry?'layanan':'daftar'}</Link></div>{publicEntry&&!isAuth&&<p className="form-notice">Isi laporan terlebih dahulu. Login akun Admin atau Staf diperlukan saat menyimpan ke server; isian sementara tetap tersimpan di tab ini.</p>}{publicEntry&&!storageAvailable&&<p className="form-error" role="alert">Penyimpanan sementara browser tidak tersedia; jangan tinggalkan halaman sebelum menyimpan isian.</p>}{error&&<p className="form-error" role="alert">{error}</p>}<form className="dash-panel managed-form" onSubmit={save} style={{display:'grid',gap:14,maxWidth:780}}>{fields.map(([key,label,type])=><label key={key}>{label}<input type={type} min={type==='number'?0:undefined} required={key==='kloter_code'} disabled={!editable} value={key==='regions'?(report.regions||[]).join(', '):type==='datetime-local'?localDateTime(report[key]):String(report[key]??'')} onChange={e=>setField(key,e.target.value,type)}/></label>)}{groups.map(group=><fieldset key={group.key} className="operations-group"><legend>{group.title}</legend>{items(group.key).map((item,index)=><div key={index} className="operations-row">{group.labels.map(label=><label key={label}>{label}<input value={item[label]||''} disabled={!editable} onChange={e=>setItem(group.key,index,label,e.target.value)}/></label>)}{editable&&<button className="btn light" type="button" onClick={()=>removeItem(group.key,index)}>Hapus baris</button>}</div>)}{editable&&<button className="btn light" type="button" onClick={()=>addItem(group.key)}>Tambah baris</button>}</fieldset>)}<label>Catatan operasional<textarea rows={4} value={String(report.notes||'')} onChange={e=>setField('notes',e.target.value,'text')} disabled={!editable}/></label><p>Rincian nama dan diagnosis hanya terlihat oleh administrator dan staf berwenang. Jangan cantumkan data jemaah dalam catatan operasional.</p>{editable&&<button className="btn primary" disabled={busy}>{busy?'Menyimpan…':!isAuth?'Login untuk simpan laporan':'Simpan draf'}</button>}</form>{!isNew&&<div className="dash-panel" style={{marginTop:16}}>{editable&&<button className="btn primary" disabled={busy} onClick={()=>void changeStatus('submitted')}>Kirim untuk ditinjau</button>}{report.status==='submitted'&&<><button className="btn primary" disabled={busy} onClick={()=>void changeStatus('reviewed')}>Tandai ditinjau</button> <button className="btn ghost" disabled={busy} onClick={()=>void changeStatus('returned')}>Kembalikan untuk perbaikan</button></>}</div>}</div>;
}
