import { useState } from 'react';
import { Link, Navigate, useSearchParams } from 'react-router-dom';
import { formContinuation, loginForForm } from '../lib/formDraft';
import { useAuth, type TravelRegistrationInput } from '../hooks/useAuth';
export default function TravelRegistration(){
 const {registerTravel,isAuth,user}=useAuth();const [params]=useSearchParams();const requested=params.get('lanjut');
 const [form,setForm]=useState<TravelRegistrationInput>({name:'',email:'',password:'',company_name:'',nib:'',office_address:''});
 const [confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const set=(key:keyof TravelRegistrationInput,value:string)=>setForm(f=>({...f,[key]:value}));
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(form.password!==confirm){setError('Konfirmasi kata sandi tidak sama.');return}setBusy(true);try{await registerTravel(form)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(isAuth&&user)return <Navigate to={formContinuation(requested,user.role)||(user.role==='travel'?'/travel/laporan-umrah':user.role==='admin'?'/admin':user.role==='staff'?'/staff':user.role==='pengawas'?'/pengawas':user.role==='konsultan'?'/konsultan':'/dashboard')} replace/>;
 return <main className="login-section video-request"><section className="login-card managed-form"><Link to={requested?loginForForm(requested):'/masuk'}>← Sudah punya akun? Masuk</Link><h1>Daftar Perusahaan Travel</h1><p>Buat akun Travel untuk mengajukan dokumen serta melaporkan keberangkatan dan pemulangan umrah.</p><form onSubmit={submit}><fieldset className="complaint-fields" disabled={busy}>{error&&<p className="form-error" role="alert">{error}</p>}<label>Nama perusahaan travel *<input required maxLength={200} value={form.company_name} onChange={e=>set('company_name',e.target.value)} autoComplete="organization"/></label><label>NIB perusahaan *<input required maxLength={40} value={form.nib} onChange={e=>set('nib',e.target.value)}/></label><label>Alamat kantor *<textarea required maxLength={1000} rows={3} value={form.office_address} onChange={e=>set('office_address',e.target.value)} autoComplete="street-address"/></label><label>Nama penanggung jawab *<input required maxLength={150} value={form.name} onChange={e=>set('name',e.target.value)} autoComplete="name"/></label><label>Email akun *<input required type="email" maxLength={200} value={form.email} onChange={e=>set('email',e.target.value)} autoComplete="email"/></label><label>Kata sandi *<input required type="password" minLength={12} maxLength={128} value={form.password} onChange={e=>set('password',e.target.value)} autoComplete="new-password"/><small>Minimal 12 karakter.</small></label><label>Ulangi kata sandi *<input required type="password" minLength={12} maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password"/></label><p>Peran akun otomatis Travel. Pendaftaran akun belum merupakan verifikasi NIB atau izin PPIU; dokumen dan layanan diperiksa petugas.</p><button className="btn primary full" disabled={busy}>{busy?'Mendaftarkan…':'Daftar dan buka laporan travel'}</button></fieldset></form></section></main>;
}
