import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { api, API_URL, getToken, expireSession, sessionExpiresAt } from '../lib/api';
import checklist from '../lib/airportChecklist.json';
const root='/operations/umrah-travel';
type Kind='DEPARTURE'|'RETURN';
type Item={code:string;result:'YES'|'NO'|null;notes:string};
type Form={airport:string;inspection_date:string;ppiu_name:string;ppiu_license_number:string;ppiu_officer_name:string;ppiu_address:string;flight_number:string;airline:string;route:string;flight_type:string;travel_date:string;pilgrim_count:string|number|null;officer_count:string|number|null;findings:string;supervised_party:string;items:Item[]};
type Review={decision:string;notes:string;supervisor_1:string;supervisor_2:string;supervised_party:string};
type Report={id:string;reference:string;kind:Kind;status:'DRAFT'|'SUBMITTED'|'FINAL';form_data:Form;review_data:Partial<Review>;updated_at:string};
type FileRow={id:string;item_code:string|null;file_name:string};
const blank=():Form=>({airport:'',inspection_date:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'}),ppiu_name:'',ppiu_license_number:'',ppiu_officer_name:'',ppiu_address:'',flight_number:'',airline:'',route:'',flight_type:'',travel_date:'',pilgrim_count:'',officer_count:'',findings:'',supervised_party:'',items:checklist.map(x=>({code:x.code,result:null,notes:''}))});
const title=(k:Kind)=>k==='DEPARTURE'?'Keberangkatan Travel Umrah':'Pemulangan Travel Umrah';
const status=(s:string)=>({DRAFT:'Draft',SUBMITTED:'Terkirim',FINAL:'Final'} as Record<string,string>)[s]||s;
function roleBase(role?:string){return role==='admin'?'/admin':role==='staff'?'/staff':role==='pengawas'?'/pengawas':'/travel'}
const decisions=(kind:Kind)=>kind==='DEPARTURE'?[['DIIZINKAN_BERANGKAT','DIIZINKAN BERANGKAT (seluruh persyaratan terpenuhi)'],['CATATAN_PERBAIKAN','CATATAN / PERBAIKAN (lengkapi dokumen minor)'],['PENUNDAAN_PENINDAKAN','PENUNDAAN / PENINDAKAN']]:[['PEMULANGAN_SELESAI','PEMULANGAN SELESAI'],['CATATAN_PERBAIKAN','CATATAN / PERBAIKAN'],['TINDAK_LANJUT','TINDAK LANJUT / PENINDAKAN']];

export function UmrahTravelList({base}:{base:string}){
 const [rows,setRows]=useState<Report[]>([]),[kind,setKind]=useState(''),[page,setPage]=useState(1),[total,setTotal]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);setError('');api<{reports:Report[];total:number}>(`${root}?page=${page}&kind=${kind}`).then(d=>{if(active){setRows(d.reports);setTotal(d.total)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[page,kind]);
 return <div className="managed-form"><div className="dash-panel-head"><h2>Laporan Travel Umrah</h2><div className="form-grid"><Link className="btn primary" to={`${base}/laporan-umrah/baru?jenis=DEPARTURE`}>+ Keberangkatan</Link><Link className="btn light" to={`${base}/laporan-umrah/baru?jenis=RETURN`}>+ Pemulangan</Link></div></div><section className="dash-panel"><label>Jenis laporan<select value={kind} onChange={e=>{setKind(e.target.value);setPage(1)}}><option value="">Semua laporan travel umrah</option><option value="DEPARTURE">Keberangkatan</option><option value="RETURN">Pemulangan</option></select></label>{error?<p className="form-error" role="alert">{error}</p>:loading?<p>Memuat…</p>:<><div className="table-wrap-live"><table className="table-live"><thead><tr><th>Referensi</th><th>Jenis</th><th>PPIU</th><th>Bandara</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.reference}</td><td>{title(r.kind)}</td><td>{r.form_data.ppiu_name}</td><td>{r.form_data.airport}</td><td>{status(r.status)}</td><td><Link className="btn light sm" to={`${base}/laporan-umrah/${r.id}`}>Buka</Link></td></tr>)}</tbody></table></div>{!rows.length&&<p>Belum ada laporan.</p>}<div className="manifest-pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Sebelumnya</button><span>Halaman {page} · {total} laporan</span><button disabled={page*25>=total} onClick={()=>setPage(p=>p+1)}>Berikutnya</button></div></>}</section></div>;
}

export function UmrahTravelForm({kind:defaultKind,base,publicEntry=false}:{kind?:Kind;base?:string;publicEntry?:boolean}){
 const {id}=useParams(),nav=useNavigate(),{user,isAuth}=useAuth();
 const kind:Kind=defaultKind||(new URLSearchParams(location.search).get('jenis')==='RETURN'?'RETURN':'DEPARTURE');
 const listBase=base||roleBase(user?.role);
 const allowed=isAuth&&Boolean(user&&['admin','staff','pengawas','travel'].includes(user.role));
 const official=Boolean(user&&['admin','staff','pengawas'].includes(user.role));
 const [form,setForm]=useState<Form>(blank),[report,setReport]=useState<Report|null>(null),[files,setFiles]=useState<FileRow[]>([]),[loading,setLoading]=useState(Boolean(id)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [review,setReview]=useState<Review>({decision:'',notes:'',supervisor_1:'',supervisor_2:'',supervised_party:''});
 useEffect(()=>{let active=true;if(!allowed)return;if(id){setLoading(true);api<{report:Report;files:FileRow[]}>(root+'/'+id).then(d=>{if(active){setReport(d.report);setForm(d.report.form_data);setFiles(d.files);setReview({decision:'',notes:'',supervisor_1:'',supervisor_2:'',supervised_party:d.report.form_data.supervised_party,...d.report.review_data})}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});}else if(user?.role==='travel'){api<{company:{name:string;office_address:string}|null}>(root+'/company').then(d=>{if(active&&d.company)setForm(f=>({...f,ppiu_name:d.company!.name,ppiu_address:d.company!.office_address||''}))}).catch(e=>{if(active)setError(e.message)});}return()=>{active=false}},[id,allowed,user?.role]);
 const currentKind=report?.kind||kind,editable=allowed&&!loading&&(!id||report!==null)&&(!report||report.status==='DRAFT');
 const set=<K extends keyof Form>(key:K,value:Form[K])=>setForm(f=>({...f,[key]:value}));
 function field(key:keyof Form,label:string,type='text',required=false){return <label>{label}{required?' *':''}<input type={type} value={String(form[key]??'')} required={required} maxLength={key==='ppiu_address'?1000:500} min={type==='number'?0:undefined} step={type==='number'?1:undefined} onChange={e=>set(key,e.target.value as Form[typeof key])}/></label>}
 async function save(){setBusy(true);setError('');setMessage('');try{const d=await api<{report:Report}>(id?root+'/'+id:root,{method:id?'PATCH':'POST',body:id?{form_data:form,updated_at:report?.updated_at}:{kind:currentKind,form_data:form}});setReport(d.report);setForm(d.report.form_data);setMessage('Draft tersimpan.');if(!id)nav(`${listBase}/laporan-umrah/${d.report.id}`,{replace:true});return d.report;}catch(e){setError((e as Error).message);return null}finally{setBusy(false)}}
 async function submit(){const saved=await save();if(!saved)return;setBusy(true);try{const d=await api<{report:Report}>(`${root}/${saved.id}/submit`,{method:'POST',body:{updated_at:saved.updated_at}});setReport(d.report);setMessage('Laporan terkirim untuk pemeriksaan petugas.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function finalize(){if(!report)return;setBusy(true);setError('');try{const d=await api<{report:Report}>(`${root}/${report.id}/finalize`,{method:'POST',body:{...review,updated_at:report.updated_at}});setReport(d.report);setMessage('Laporan difinalisasi; rekomendasi dan ketiga nama tersimpan bersama.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function upload(file:File,code?:string){if(!report)return;setBusy(true);setError('');try{if(file.size>8388608||!['image/jpeg','image/png','application/pdf'].includes(file.type))throw Error('Gunakan JPG, PNG, atau PDF maksimal 8 MB.');const token=getToken();if(!token)throw Error('Silakan masuk kembali.');if((sessionExpiresAt(token)??0)<=Date.now()){expireSession(token);throw Error('Sesi telah berakhir.');}const headers:Record<string,string>={'Content-Type':'application/octet-stream','Authorization':'Bearer '+token,'x-file-type':file.type,'x-file-name':encodeURIComponent(file.name)};if(code)headers['x-item-code']=code;const r=await fetch(`${API_URL}${root}/${report.id}/files`,{method:'POST',headers,body:file});if(r.status===401)expireSession(token);const d=await r.json();if(!r.ok)throw Error(d.error||'Unggah gagal.');setFiles(a=>[...a,d.file]);setMessage('Bukti tersimpan privat.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function view(file:FileRow){try{const d=await api<{url:string}>(`${root}/${report!.id}/files/${file.id}/url`);window.location.assign(d.url)}catch(e){setError((e as Error).message)}}
 const content=<div className="managed-form"><Link to={publicEntry?'/layanan?category=Pelaporan':`${listBase}/laporan-umrah`}>← {publicEntry?'Layanan pelaporan':'Daftar laporan travel umrah'}</Link><h1>Pelaporan {title(currentKind)}</h1><p>Instrumen Pemantauan dan Pengawasan PPIU di Bandara.</p>{publicEntry&&!allowed&&<div className="form-notice">Masuk sebagai perusahaan travel atau petugas untuk mengisi dan menyimpan laporan. <Link to={`/masuk?lanjut=${encodeURIComponent(location.pathname)}`}>Masuk</Link> · <Link to="/daftar-travel">Daftar perusahaan travel</Link></div>}{currentKind==='RETURN'&&<p>Form pemulangan menggunakan indikator dokumen dan layanan yang sama. Indikator sebelum keberangkatan dinilai terhadap perjalanan yang dilaporkan; rekomendasi akhir disesuaikan untuk pemulangan.</p>}{report&&<p><b>{report.reference}</b> · {status(report.status)}</p>}{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="form-notice" role="status">{message}</p>}{loading?<p>Memuat…</p>:<>
 <fieldset className="complaint-fields" disabled={!editable||busy}><fieldset className="operations-group"><legend>Bandara dan Waktu Pelaporan</legend><div className="form-grid"><label>Bandara *<select value={form.airport==='Soekarno Hatta'?'Soekarno Hatta':form.airport?'Lainnya':''} onChange={e=>set('airport',e.target.value==='Lainnya'?'Bandara lainnya':e.target.value)}><option value="">Pilih bandara</option><option>Soekarno Hatta</option><option>Lainnya</option></select></label>{form.airport&&form.airport!=='Soekarno Hatta'&&field('airport','Nama bandara lainnya','text',true)}{field('inspection_date','Tanggal pemeriksaan/pelaporan','date',true)}{field('travel_date',currentKind==='DEPARTURE'?'Tanggal keberangkatan':'Tanggal pemulangan','date',true)}</div></fieldset>
 <fieldset className="operations-group"><legend>I. Data Identitas dan Administrasi Penyelenggara</legend><div className="form-grid">{field('ppiu_name','Nama PPIU','text',true)}{field('ppiu_license_number','Nomor Izin Berusaha PPIU','text',true)}{field('ppiu_officer_name','Nama Pimpinan/Petugas','text',true)}{field('ppiu_address','Alamat Kantor/PPIU Pusat','text',true)}{field('flight_number','Nomor penerbangan','text',true)}{field('airline','Maskapai','text',true)}{field('route','Rute penerbangan (asal → tujuan)','text',true)}<label>Jenis penerbangan *<select value={form.flight_type} onChange={e=>set('flight_type',e.target.value)}><option value="">Pilih rute</option><option value="DIRECT">Direct (langsung)</option><option value="TRANSIT">Transit 1 kali (maksimal 2 maskapai)</option></select></label>{field('pilgrim_count','Jumlah jemaah','number',true)}{field('officer_count','Jumlah petugas','number',true)}</div><p><b>Total: {Number(form.pilgrim_count||0)+Number(form.officer_count||0)} jemaah dan petugas</b></p></fieldset>
 {[...new Set(checklist.map(x=>x.section))].map(section=><fieldset className="operations-group" key={section}><legend>{section}</legend>{checklist.filter(x=>x.section===section).map(x=>{const item=form.items.find(i=>i.code===x.code)!;return <section className="airport-indicator" key={x.code}><h3>{x.indicator}</h3><div className="form-grid"><label>Memenuhi *<select value={item.result||''} onChange={e=>set('items',form.items.map(i=>i.code===x.code?{...i,result:e.target.value as Item['result']}:i))}><option value="">Pilih Iya / Tidak</option><option value="YES">Iya</option><option value="NO">Tidak</option></select></label><label>Catatan dan bukti dokumen/foto<textarea rows={3} maxLength={2000} placeholder={x.evidence} value={item.notes} onChange={e=>set('items',form.items.map(i=>i.code===x.code?{...i,notes:e.target.value}:i))}/></label></div><p>{x.evidence}</p>{report?<label>Unggah bukti (JPG/PNG/PDF, maksimal 8 MB)<input type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file,x.code);e.target.value=''}}/></label>:<p>Simpan draft terlebih dahulu untuk mengunggah bukti.</p>}</section>})}</fieldset>)}
 <fieldset className="operations-group"><legend>V. Rekapitulasi Evaluasi dan Temuan Khusus</legend><label>Catatan / deskripsi temuan lapangan<textarea rows={5} maxLength={4000} value={form.findings} onChange={e=>set('findings',e.target.value)}/></label>{field('supervised_party','Pihak yang diawasi: Pimpinan/Petugas PPIU','text',true)}<p>Rekomendasi dan identitas pengawas dicatat petugas setelah laporan dikirim.</p></fieldset></fieldset>
 <section className="dash-panel spaced-panel"><h3>Catatan peraturan dalam instrumen PDF</h3><p>Pengumpulan atau pemberangkatan jemaah umrah oleh pihak tanpa izin PPIU yang sah dapat dikenakan pidana penjara paling lama 6 tahun dan/atau denda (Pasal 122 UU No. 14 Tahun 2025).</p><p>Tindakan tanpa hak mengambil sebagian/seluruh setoran Jemaah Umrah dipidana penjara paling lama 8 tahun (Pasal 124 UU No. 14 Tahun 2025).</p></section>
 <section className="dash-panel spaced-panel"><h3>Bukti tersimpan</h3>{files.map(f=><p key={f.id}><button type="button" className="btn light" disabled={busy} onClick={()=>view(f)}>{f.item_code||'Umum'} · {f.file_name}</button></p>)}{!files.length&&<p>Belum ada berkas.</p>}</section>
 <fieldset className="operations-group spaced-panel" disabled={!official||report?.status!=='SUBMITTED'||busy}><legend>Rekomendasi Pengawas</legend><label>Rekomendasi<select value={review.decision} onChange={e=>setReview({...review,decision:e.target.value})}><option value="">Pilih rekomendasi</option>{decisions(currentKind).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Catatan<textarea rows={5} maxLength={4000} value={review.notes} onChange={e=>setReview({...review,notes:e.target.value})}/></label><div className="form-grid">{(['supervisor_1','supervisor_2','supervised_party'] as const).map((key,i)=><label key={key}>{['Pengawas Kementerian Haji dan Umrah — Pengawas 1','Pengawas 2','Pihak yang diawasi — Pimpinan/Petugas PPIU'][i]}<input maxLength={150} value={review[key]} onChange={e=>setReview({...review,[key]:e.target.value})}/></label>)}</div>{official&&report?.status==='SUBMITTED'&&<button type="button" className="btn primary" onClick={finalize}>Finalisasi laporan</button>}</fieldset>
 {editable&&<div className="airport-actions"><button type="button" className="btn light" disabled={busy} onClick={save}>Simpan draft</button>{id&&<button type="button" className="btn primary" disabled={busy} onClick={submit}>Simpan dan kirim laporan</button>}</div>}
 </>}</div>;
 return publicEntry?<main className="section complaint-page"><div className="container">{content}</div></main>:content;
}
