import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams, useLocation } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { api } from '../lib/api';
import allChecklist from '../lib/airportChecklist.json';
const returnGuidance={code:'RET-01',section:'IV. Pengawasan Bimbingan',indicator:'Jemaah telah menerima sosialisasi/edukasi persiapan kepulangan Umrah dari PPIU.',evidence:'Wawancara jemaah/petugas'};
const checklist=allChecklist.filter(x=>x.code!=='DOC-05');
import { useFormDraft } from '../hooks/useFormDraft';
import { loginForForm, registrationForForm } from '../lib/formDraft';
function validDriveLink(value:string){try{const url=new URL(value.trim());return url.protocol==='https:'&&['drive.google.com','docs.google.com'].includes(url.hostname)&&!url.username&&!url.password}catch{return false}}
const root='/operations/umrah-travel';
type Kind='DEPARTURE'|'RETURN';
type Item={code:string;result:'YES'|'NO'|null;notes:string;drive_url?:string};
type Form={drive_url?:string;airport:string;inspection_date:string;ppiu_name:string;ppiu_license_number:string;ppiu_officer_name:string;ppiu_address:string;flight_number:string;airline:string;route:string;flight_type:string;travel_date:string;pilgrim_count:string|number|null;officer_count:string|number|null;findings:string;supervised_party:string;items:Item[];departure_source_id?:string};
type Verification={code:string;result:'YES'|'NO'|null};
const blankVerification=():Verification[]=>checklist.map(x=>({code:x.code,result:null}));
type Review={reviewer_name?:string;verification_items?:Verification[];decision:string;notes:string;supervisor_1:string;supervisor_2:string;supervised_party:string};
type Report={id:string;reference:string;kind:Kind;status:'DRAFT'|'SUBMITTED'|'FINAL';form_data:Form;review_data:Partial<Review>;updated_at:string;departure_report_id?:string|null;departure_reference?:string|null;departure_snapshot?:Form|null;reviewed_by?:string|null;finalized_at?:string|null};

const blank=():Form=>({airport:'',inspection_date:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'}),ppiu_name:'',ppiu_license_number:'',ppiu_officer_name:'',ppiu_address:'',flight_number:'',airline:'',route:'',flight_type:'',travel_date:'',pilgrim_count:'',officer_count:'',findings:'',supervised_party:'',items:[...checklist,returnGuidance].map(x=>({code:x.code,result:null,notes:'',drive_url:''}))});
function validDraft(value:unknown,kind:Kind='DEPARTURE'){if(!value||typeof value!=='object')return false;const f=value as Form;return Object.keys(blank()).every(k=>k in f)&&Array.isArray(f.items)&&checklist.filter(x=>kind!=='RETURN'||!x.code.startsWith('BIM-')).every(x=>f.items.some(i=>i&&i.code===x.code&&typeof i.notes==='string'&&[null,'YES','NO'].includes(i.result)))}
const title=(k:Kind)=>k==='DEPARTURE'?'Keberangkatan Travel Umrah':'Pemulangan Travel Umrah';
const status=(s:string)=>({DRAFT:'Draft',SUBMITTED:'Terkirim',FINAL:'Final'} as Record<string,string>)[s]||s;
function roleBase(role?:string){return role==='admin'?'/admin':role==='staff'?'/staff':role==='pengawas'?'/pengawas':'/travel'}
const decisions=(kind:Kind)=>kind==='DEPARTURE'?[['DIIZINKAN_BERANGKAT','DIIZINKAN BERANGKAT (seluruh persyaratan terpenuhi)'],['CATATAN_PERBAIKAN','CATATAN / PERBAIKAN (lengkapi dokumen minor)'],['PENUNDAAN_PENINDAKAN','PENUNDAAN / PENINDAKAN']]:[['PEMULANGAN_SELESAI','PEMULANGAN SELESAI'],['CATATAN_PERBAIKAN','CATATAN / PERBAIKAN'],['TINDAK_LANJUT','TINDAK LANJUT / PENINDAKAN']];

export function ActionFeedback({error,message}:{error:string;message:string}) {
 const [dismissed,setDismissed]=useState(false);
 useEffect(()=>setDismissed(false),[error,message]);
 const notice=error||message;
 if(!notice||dismissed)return null;
 return <aside aria-label="Notifikasi laporan" style={{position:'fixed',right:16,bottom:24,width:'min(540px, calc(100vw - 32px))',maxHeight:'40vh',overflowY:'auto',zIndex:2000,padding:20,borderRadius:12,boxShadow:'0 8px 32px #0003',background:error?'#fff1f0':'#eef7ef',color:error?'#8f211c':'#245a32',border:'1px solid '+(error?'#efb8b4':'#bed9c2'),fontSize:16,lineHeight:1.6}}>
  <button type="button" aria-label="Tutup notifikasi" onClick={()=>setDismissed(true)} style={{float:'right',marginLeft:12,padding:'4px 8px',background:'transparent',border:'1px solid currentColor',borderRadius:6,color:'inherit',cursor:'pointer'}}>Tutup</button>
  <div role={error?'alert':'status'} aria-live={error?'assertive':'polite'} aria-atomic="true"><strong>{error?'Perlu perhatian':'Berhasil'}</strong><p style={{margin:'8px 0 0',overflowWrap:'anywhere'}}>{notice}</p></div>
 </aside>;
}

export function EvidenceUpload({indicator,disabled,onFile,label='Unggah bukti (JPG/PNG/PDF, maksimal 8 MB)',accept='image/jpeg,image/png,application/pdf'}:{indicator:string;disabled:boolean;onFile:(file:File)=>void;label?:string;accept?:string}) {
 const input=useRef<HTMLInputElement>(null);
 return <div><p>{label}</p><button type="button" className="btn light" disabled={disabled} onClick={()=>input.current?.click()} style={{display:'inline-flex',minHeight:48,fontSize:16}}>Pilih berkas</button><input ref={input} type="file" aria-label={`Unggah bukti ${indicator}`} hidden style={{display:'none'}} accept={accept} disabled={disabled} onChange={e=>{const file=e.target.files?.[0];if(file)onFile(file);e.target.value=''}}/></div>;
}

export function UmrahTravelList({base}:{base:string}){
 const [rows,setRows]=useState<Report[]>([]),[kind,setKind]=useState(''),[page,setPage]=useState(1),[total,setTotal]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);setError('');api<{reports:Report[];total:number}>(`${root}?page=${page}&kind=${kind}`).then(d=>{if(active){setRows(d.reports);setTotal(d.total)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[page,kind]);
 return <div className="managed-form"><div className="dash-panel-head"><h2>Laporan Travel Umrah</h2><div className="form-grid"><button type="button" className={`btn ${kind==='DEPARTURE'?'primary':'light'}`} aria-pressed={kind==='DEPARTURE'} onClick={()=>{setKind('DEPARTURE');setPage(1)}}>Keberangkatan</button><button type="button" className={`btn ${kind==='RETURN'?'primary':'light'}`} aria-pressed={kind==='RETURN'} onClick={()=>{setKind('RETURN');setPage(1)}}>Pemulangan</button></div></div><section className="dash-panel"><div className="dash-panel-head"><h3>{kind==='RETURN'?'Daftar laporan pemulangan':kind==='DEPARTURE'?'Daftar laporan keberangkatan':'Semua laporan travel umrah'}</h3><div className="form-grid">{kind!=='RETURN'&&<Link className="btn light" to={`${base}/laporan-umrah/baru?jenis=DEPARTURE`}>Buat laporan keberangkatan</Link>}{kind!=='DEPARTURE'&&<Link className="btn light" to={`${base}/laporan-umrah/baru?jenis=RETURN`}>Buat laporan pemulangan</Link>}</div></div><label>Jenis laporan<select value={kind} onChange={e=>{setKind(e.target.value);setPage(1)}}><option value="">Semua laporan travel umrah</option><option value="DEPARTURE">Keberangkatan</option><option value="RETURN">Pemulangan</option></select></label>{error?<p className="form-error" role="alert">{error}</p>:loading?<p>Memuat…</p>:<><div className="table-wrap-live"><table className="table-live"><thead><tr><th>Referensi</th><th>Jenis</th><th>PPIU</th><th>Bandara</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.reference}</td><td>{title(r.kind)}</td><td>{r.form_data.ppiu_name}</td><td>{r.form_data.airport}</td><td>{status(r.status)}</td><td><Link className="btn light sm" to={`${base}/laporan-umrah/${r.id}`}>Buka</Link></td></tr>)}</tbody></table></div>{!rows.length&&<p>Belum ada laporan.</p>}<div className="manifest-pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Sebelumnya</button><span>Halaman {page} · {total} laporan</span><button disabled={page*25>=total} onClick={()=>setPage(p=>p+1)}>Berikutnya</button></div></>}</section></div>;
}

export function UmrahTravelForm({kind:defaultKind,base,publicEntry=false}:{kind?:Kind;base?:string;publicEntry?:boolean}){
 const route=useLocation();const {id}=useParams(),nav=useNavigate(),{user,isAuth}=useAuth();
 const kind:Kind=defaultKind||(new URLSearchParams(location.search).get('jenis')==='RETURN'?'RETURN':'DEPARTURE');
 const listBase=base||roleBase(user?.role);
 const allowed=isAuth&&Boolean(user&&['admin','staff','pengawas','travel'].includes(user.role));
 const official=Boolean(user&&['admin','staff','pengawas'].includes(user.role));
 const {value:form,setValue:setForm,persist,clear,storageAvailable}=useFormDraft<Form>('umrah-'+kind,publicEntry&&!id,blank,v=>validDraft(v,kind));
 const [report,setReport]=useState<Report|null>(null),[loading,setLoading]=useState(Boolean(id)),[busy,setBusy]=useState(false),[error,setError]=useState<string>(route.state?.submitError||''),[message,setMessage]=useState<string>(route.state?.actionMessage||'');
 useEffect(()=>{setError(route.state?.submitError||'');setMessage(route.state?.actionMessage||'')},[route.key]);

 const [departures,setDepartures]=useState<Report[]>([]),[source,setSource]=useState<Report|null>(null),[sourcePage,setSourcePage]=useState(1),[sourceTotal,setSourceTotal]=useState(0);
 const requestedSource=form.departure_source_id||new URLSearchParams(location.search).get('keberangkatan');
 useEffect(()=>{if(!allowed||id||kind!=='RETURN')return;let active=true;api<{reports:Report[];total:number}>(`${root}?for_return=true&page=${sourcePage}`).then(d=>{if(active){setDepartures(d.reports);setSourceTotal(d.total)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[allowed,id,kind,sourcePage]);
 function selectDeparture(d:Report){setSource(d);const inherited=d.form_data;setForm(f=>({...f,drive_url:f.drive_url||inherited.drive_url||'',departure_source_id:d.id,ppiu_name:inherited.ppiu_name,ppiu_license_number:inherited.ppiu_license_number,ppiu_address:inherited.ppiu_address,ppiu_officer_name:f.ppiu_officer_name||inherited.ppiu_officer_name,supervised_party:f.supervised_party||inherited.supervised_party,pilgrim_count:f.pilgrim_count===''||f.pilgrim_count==null?inherited.pilgrim_count:f.pilgrim_count,officer_count:f.officer_count===''||f.officer_count==null?inherited.officer_count:f.officer_count,items:f.items.map(i=>{const from=inherited.items.find(x=>x.code===i.code);return {...i,result:i.result||from?.result||null,notes:i.notes||from?.notes||'',drive_url:i.drive_url||from?.drive_url||''}})}));setMessage('Data PPIU, jumlah peserta, dan indikator diambil dari keberangkatan. Lengkapi penerbangan, tanggal, serta kondisi kepulangan.')}
 useEffect(()=>{if(!allowed||id||kind!=='RETURN'||!requestedSource)return;let active=true;api<{report:Report}>(root+'/'+requestedSource).then(d=>{if(active){if(d.report.kind==='DEPARTURE'&&d.report.status==='FINAL'&&d.report.review_data.decision==='DIIZINKAN_BERANGKAT')selectDeparture(d.report);else setError('Keberangkatan belum final/diizinkan.')}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[allowed,id,kind,requestedSource]);
 const [review,setReview]=useState<Review>({verification_items:blankVerification(),decision:'',notes:'',supervisor_1:'',supervisor_2:'',supervised_party:''});
 useEffect(()=>{let active=true;if(!allowed)return;if(id){setLoading(true);api<{report:Report}>(root+'/'+id).then(d=>{if(active){setReport(d.report);setForm({...d.report.form_data,items:[...checklist,returnGuidance].map(x=>d.report.form_data.items.find(i=>i.code===x.code)||{code:x.code,result:null,notes:'',drive_url:''})});setReview({verification_items:blankVerification(),decision:'',notes:'',supervisor_1:'',supervisor_2:'',supervised_party:d.report.form_data.supervised_party,...d.report.review_data})}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});}else if(user?.role==='travel'){api<{company:{name:string;office_address:string}|null}>(root+'/company').then(d=>{if(active&&d.company)setForm(f=>({...f,ppiu_name:f.ppiu_name||d.company!.name,ppiu_address:f.ppiu_address||d.company!.office_address||''}))}).catch(e=>{if(active)setError(e.message)});}return()=>{active=false}},[id,allowed,user?.role]);
 const currentKind=report?.kind||kind;
 const checklist=currentKind==='RETURN'?[...allChecklist.filter(x=>x.code!=='DOC-05'&&!x.code.startsWith('BIM-')),returnGuidance]:allChecklist.filter(x=>x.code!=='DOC-05');
 const editable=(allowed||(publicEntry&&!id))&&!loading&&(!id||report!==null)&&(!report||report.status==='DRAFT');
 const set=<K extends keyof Form>(key:K,value:Form[K])=>setForm(f=>({...f,[key]:value}));
 function field(key:keyof Form,label:string,type='text',required=false){const inherited=currentKind==='RETURN'&&Boolean(source||report?.departure_report_id)&&['ppiu_name','ppiu_license_number','ppiu_address'].includes(key);return <label>{label}{required?' *':''}<input type={type} readOnly={inherited} value={String(form[key]??'')} required={required} maxLength={key==='ppiu_address'?1000:500} min={type==='number'?0:undefined} step={type==='number'?1:undefined} onChange={e=>set(key,e.target.value as Form[typeof key])}/></label>}
 function requireAccount(){if(!isAuth){if(!persist()){setError('Penyimpanan sementara browser tidak tersedia. Aktifkan penyimpanan browser sebelum login agar isian tidak hilang.');return false}nav(loginForForm(location.pathname));return false}if(!allowed){setError('Gunakan akun Travel, Admin, Staf, atau Pengawas untuk mengirim laporan ini. Isian tetap tersimpan.');return false}return true}
 async function save(redirect=true){if(!requireAccount())return null;if((form.drive_url?.trim()&&!validDriveLink(form.drive_url))||form.items.some(i=>i.drive_url?.trim()&&!validDriveLink(i.drive_url))){setError('Gunakan link HTTPS Google Drive atau Google Docs yang valid.');return null}if(currentKind==='RETURN'&&!id&&!source){setError('Pilih laporan keberangkatan terlebih dahulu.');return null}setBusy(true);setError('');setMessage('');try{const d=await api<{report:Report}>((id||report?.id)?root+'/'+(id||report?.id):root,{method:(id||report?.id)?'PATCH':'POST',body:(id||report?.id)?{form_data:form,updated_at:report?.updated_at}:{kind:currentKind,form_data:form,departure_report_id:source?.id}});setReport(d.report);setForm({...d.report.form_data,items:[...checklist,returnGuidance].map(x=>d.report.form_data.items.find(i=>i.code===x.code)||{code:x.code,result:null,notes:'',drive_url:''})});if(redirect)setMessage('Draft tersimpan.');if(!id&&redirect){clear();nav(`${listBase}/laporan-umrah/${d.report.id}`,{replace:true,state:{actionMessage:'Draft tersimpan.'}});}return d.report;}catch(e){setError((e as Error).message);return null}finally{setBusy(false)}}
 async function submit(){const saved=await save(false);if(!saved)return;setBusy(true);setError('');try{const d=await api<{report:Report}>(`${root}/${saved.id}/submit`,{method:'POST',body:{updated_at:saved.updated_at}});setReport(d.report);setMessage('Laporan dan link dokumen terkirim untuk pemeriksaan petugas.');clear();if(!id)nav(`${listBase}/laporan-umrah/${d.report.id}`,{replace:true,state:{actionMessage:'Laporan dan link dokumen terkirim untuk pemeriksaan petugas.'}})}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function finalize(){if(!report)return;if(!review.verification_items||checklist.some(x=>!review.verification_items?.find(i=>i.code===x.code)?.result)){setError('Lengkapi hasil pemeriksaan petugas untuk seluruh indikator sebelum finalisasi.');return}setBusy(true);setError('');setMessage('');try{const d=await api<{report:Report}>(`${root}/${report.id}/finalize`,{method:'POST',body:{...review,verification_items:review.verification_items.filter(i=>checklist.some(x=>x.code===i.code)),updated_at:report.updated_at}});setReport(d.report);setMessage('Laporan difinalisasi; rekomendasi dan ketiga nama tersimpan bersama.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const content=<div className="managed-form"><ActionFeedback error={error} message={message}/><Link to={publicEntry?'/layanan?category=Pelaporan':`${listBase}/laporan-umrah`}>← {publicEntry?'Layanan pelaporan':'Daftar laporan travel umrah'}</Link><h1>Pelaporan {title(currentKind)}</h1><p>Instrumen Pemantauan dan Pengawasan PPIU di Bandara.</p>{publicEntry&&!allowed&&<div className="form-notice">Isi formulir terlebih dahulu. Login diperlukan saat mengirim laporan atau menyimpan draft ke server. Isian sementara disimpan di tab ini. <Link to={loginForForm(location.pathname)} onClick={e=>{if(!persist())e.preventDefault()}}>Masuk</Link> · <Link to={registrationForForm(location.pathname)} onClick={e=>{if(!persist())e.preventDefault()}}>Daftar perusahaan travel</Link></div>}{publicEntry&&!storageAvailable&&<p className="form-error" role="alert">Penyimpanan sementara browser tidak tersedia; jangan tinggalkan halaman sebelum menyimpan isian.</p>}{currentKind==='RETURN'&&<p>Form pemulangan menggunakan indikator dokumen dan layanan yang sama. Indikator sebelum keberangkatan dinilai terhadap perjalanan yang dilaporkan.</p>}{currentKind==='RETURN'&&!id&&<section className="dash-panel spaced-panel"><h3>Data dari laporan keberangkatan</h3>{!allowed?<p>Isian dapat disiapkan sekarang. Setelah login, pilih laporan keberangkatan perusahaan Anda sebagai sumber.</p>:<><label>Laporan keberangkatan final<select value={source?.id||''} onChange={e=>{const d=departures.find(r=>r.id===e.target.value);if(d)selectDeparture(d)}}><option value="">Pilih keberangkatan yang diizinkan berangkat</option>{source&&!departures.some(d=>d.id===source.id)&&<option value={source.id}>{source.reference}</option>}{departures.map(d=><option key={d.id} value={d.id}>{d.reference} · {d.form_data.ppiu_name} · {d.form_data.travel_date}</option>)}</select></label>{!departures.length&&<p>Belum ada keberangkatan final yang diizinkan berangkat.</p>}<div className="manifest-pagination"><button type="button" disabled={sourcePage===1} onClick={()=>setSourcePage(p=>p-1)}>Sebelumnya</button><span>Halaman {sourcePage}</span><button type="button" disabled={sourcePage*25>=sourceTotal} onClick={()=>setSourcePage(p=>p+1)}>Berikutnya</button></div></>}{source&&<p>Sumber: <b>{source.reference}</b>. Data keberangkatan asli tetap tersimpan.</p>}</section>}{report?.departure_report_id&&<p>Keberangkatan sumber: <Link to={`${listBase}/laporan-umrah/${report.departure_report_id}`}>{report.departure_reference||report.departure_report_id}</Link></p>}{report&&<p><b>{report.reference}</b> · {status(report.status)}</p>}{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="form-notice" role="status">{message}</p>}{loading?<p>Memuat…</p>:<>
 <fieldset className="complaint-fields" disabled={!editable||busy}><fieldset className="operations-group"><legend>Bandara dan Waktu Pelaporan</legend><div className="form-grid"><label>Bandara *<select value={form.airport==='Soekarno Hatta'?'Soekarno Hatta':form.airport?'Lainnya':''} onChange={e=>set('airport',e.target.value==='Lainnya'?'Bandara lainnya':e.target.value)}><option value="">Pilih bandara</option><option>Soekarno Hatta</option><option>Lainnya</option></select></label>{form.airport&&form.airport!=='Soekarno Hatta'&&field('airport','Nama bandara lainnya','text',true)}{field('inspection_date','Tanggal pemeriksaan/pelaporan','date',true)}{field('travel_date',currentKind==='DEPARTURE'?'Tanggal keberangkatan':'Tanggal pemulangan','date',true)}</div></fieldset>
 <fieldset className="operations-group"><legend>I. Data Identitas dan Administrasi Penyelenggara</legend><div className="form-grid">{field('ppiu_name','Nama PPIU','text',true)}{field('ppiu_license_number','Nomor Izin Berusaha PPIU','text',true)}{field('ppiu_officer_name','Nama Pimpinan/Petugas','text',true)}{field('ppiu_address','Alamat Kantor/PPIU Pusat','text',true)}{field('flight_number','Nomor penerbangan','text',true)}{field('airline','Maskapai','text',true)}{field('route','Rute penerbangan (asal → tujuan)','text',true)}<label>Jenis penerbangan *<select value={form.flight_type} onChange={e=>set('flight_type',e.target.value)}><option value="">Pilih rute</option><option value="DIRECT">Direct (langsung)</option><option value="TRANSIT">Transit 1 kali (maksimal 2 maskapai)</option></select></label>{field('pilgrim_count','Jumlah jemaah','number',true)}{field('officer_count','Jumlah petugas','number',true)}</div><p><b>Total: {Number(form.pilgrim_count||0)+Number(form.officer_count||0)} jemaah dan petugas</b></p></fieldset>
 <fieldset className="operations-group"><legend>Dokumen Pendukung</legend><label>Link folder Google Drive<input type="url" inputMode="url" maxLength={2000} placeholder="https://drive.google.com/drive/folders/..." disabled={!allowed} value={form.drive_url||''} onChange={e=>set('drive_url',e.target.value)}/></label><p>Cukup satu folder untuk seluruh dokumen laporan ini. Pisahkan manifest, paspor, visa, dan dokumen lainnya ke subfolder. Pastikan petugas pemeriksa mendapat akses lihat; sesuaikan dokumen untuk perjalanan yang dilaporkan.</p>{!allowed&&<p>Login terlebih dahulu untuk mengisi link dokumen.</p>}{form.drive_url&&validDriveLink(form.drive_url)&&<p><a className="btn light" href={form.drive_url.trim()} target="_blank" rel="noopener noreferrer">Buka folder Google Drive</a></p>}{form.items.some(i=>i.drive_url)&&<details><summary>Link dokumen sebelumnya</summary>{form.items.filter(i=>i.drive_url&&validDriveLink(i.drive_url)).map(i=><p key={i.code}><a href={i.drive_url!.trim()} target="_blank" rel="noopener noreferrer">{checklist.find(x=>x.code===i.code)?.indicator||i.code}</a></p>)}</details>}</fieldset>
 {[...new Set(checklist.map(x=>x.section))].map(section=><fieldset className="operations-group" key={section}><legend>{section}</legend>{checklist.filter(x=>x.section===section).map(x=>{const item=form.items.find(i=>i.code===x.code)||{code:x.code,result:null,notes:''};return <section className="airport-indicator" key={x.code}><h3>{x.indicator}</h3><div className="form-grid"><label>Pernyataan Travel — Memenuhi *<select value={item.result||''} onChange={e=>set('items',[...form.items.filter(i=>i.code!==x.code),{...item,result:e.target.value as Item['result']}])}><option value="">Pilih Iya / Tidak</option><option value="YES">Iya</option><option value="NO">Tidak</option></select></label></div><p>{x.evidence}</p></section>})}</fieldset>)}
 <fieldset className="operations-group"><legend>Perwakilan PPIU</legend>{field('supervised_party','Nama Pimpinan/Petugas PPIU','text',true)}</fieldset></fieldset>
 <section className="dash-panel spaced-panel"><p>Pengumpulan atau pemberangkatan jemaah umrah oleh pihak tanpa izin PPIU yang sah dapat dikenakan pidana penjara paling lama 6 tahun dan/atau denda (Pasal 122 UU No. 14 Tahun 2025).</p><p>Tindakan tanpa hak mengambil sebagian/seluruh setoran Jemaah Umrah dipidana penjara paling lama 8 tahun (Pasal 124 UU No. 14 Tahun 2025).</p></section>
 {official&&report&&report.status!=='DRAFT'&&<section className="dash-panel spaced-panel"><h3>Hasil Pemeriksaan Petugas</h3>{form.findings&&<p>Temuan pada laporan sebelumnya: {form.findings}</p>}<p>Dicatat oleh Admin, Staf, atau Pengawas setelah pemeriksaan dokumen / wawancara. Hasil ini terpisah dari pernyataan travel dan disimpan saat finalisasi.</p>{checklist.map(x=>{const stated=form.items.find(i=>i.code===x.code);const checked=review.verification_items?.find(i=>i.code===x.code);return <div className="airport-indicator" key={x.code}><h4>{x.indicator}</h4><p>Pernyataan travel: {stated?.result==='YES'?'Iya':stated?.result==='NO'?'Tidak':'Belum diisi'}</p>{stated?.drive_url&&validDriveLink(stated.drive_url)&&<a className="btn light" href={stated.drive_url} target="_blank" rel="noopener noreferrer">Buka dokumen Google Drive</a>}<label>Hasil pemeriksaan petugas<select disabled={!official||report.status!=='SUBMITTED'||busy} value={checked?.result||''} onChange={e=>setReview(r=>({...r,verification_items:(r.verification_items||blankVerification()).map(i=>i.code===x.code?{...i,result:e.target.value as Verification['result']}:i)}))}><option value="">Belum diperiksa</option><option value="YES">Memenuhi</option><option value="NO">Tidak memenuhi</option></select></label></div>})}{report.finalized_at&&<p>Finalisasi: {new Date(report.finalized_at).toLocaleString('id-ID')} · Petugas: {review.reviewer_name||report.reviewed_by||'Tidak tercatat'}</p>}</section>}
 {official&&<fieldset className="operations-group spaced-panel" disabled={!official||report?.status!=='SUBMITTED'||busy}><legend>Rekomendasi Pengawas</legend><label>Rekomendasi<select value={review.decision} onChange={e=>setReview({...review,decision:e.target.value})}><option value="">Pilih rekomendasi</option>{decisions(currentKind).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Catatan<textarea rows={5} maxLength={4000} value={review.notes} onChange={e=>setReview({...review,notes:e.target.value})}/></label><div className="form-grid">{(['supervisor_1','supervisor_2','supervised_party'] as const).map((key,i)=><label key={key}>{['Pengawas Kementerian Haji dan Umrah — Pengawas 1','Pengawas 2','Pihak yang diawasi — Pimpinan/Petugas PPIU'][i]}<input maxLength={150} value={review[key]} onChange={e=>setReview({...review,[key]:e.target.value})}/></label>)}</div>{official&&report?.status==='SUBMITTED'&&<button type="button" className="btn primary" onClick={finalize}>Finalisasi laporan</button>}</fieldset>}
 {report?.kind==='DEPARTURE'&&report.status==='FINAL'&&report.review_data.decision==='DIIZINKAN_BERANGKAT'&&<Link className="btn primary" to={`${listBase}/laporan-umrah/baru?jenis=RETURN&keberangkatan=${report.id}`}>Buat laporan pemulangan dari keberangkatan ini</Link>}{editable&&<div className="airport-actions"><button type="button" className="btn light" disabled={busy} onClick={()=>{if(publicEntry&&!isAuth){if(persist())setMessage('Draft tersimpan sementara di tab ini. Login hanya diperlukan untuk menyimpan ke server.')}else void save()}}>Simpan draft</button>{(id||publicEntry)&&<button type="button" className="btn primary" disabled={busy} onClick={submit}>{!isAuth?'Login untuk kirim laporan':'Simpan dan kirim laporan'}</button>}</div>}
 </>}</div>;
 return publicEntry?<main className="section complaint-page"><div className="container">{content}</div></main>:content;
}
