import{useEffect,useId}from'react';import{Link,NavLink}from'react-router-dom';import{ArrowRight,ChevronRight,Menu,MoonStar,X}from'lucide-react';import type{ButtonHTMLAttributes,ReactNode}from'react';
export function Logo({light=false}:{light?:boolean}){return <Link to="/" className={'logo '+(light?'light':'')} aria-label="KEMENHAJ Riau, beranda"><span className="logo-mark"><MoonStar/></span><span>KEMENHAJ <i>Purwarupa</i><small>Layanan Konsultasi Haji dan Umrah · Riau</small></span></Link>}
export function Button({children,variant='primary',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'danger'}){return <button {...props} className={`btn ${variant}`}>{children}<ArrowRight size={17}/></button>}
export function Container({children,className=''}:{children:ReactNode,className?:string}){return <div className={'container '+className}>{children}</div>}
export function SectionHeading({eyebrow,title,description,center=false}:{eyebrow?:string,title:string,description?:string,center?:boolean}){return <div className={'section-title '+(center?'center':'')}>{eyebrow&&<span>{eyebrow}</span>}<h2>{title}</h2>{description&&<p>{description}</p>}</div>}
export function Breadcrumb({items}:{items:{label:string,to?:string}[]}){return <nav className="breadcrumb" aria-label="Breadcrumb"><Link to="/">Beranda</Link>{items.map(x=><span key={x.label}><ChevronRight/>{x.to?<Link to={x.to}>{x.label}</Link>:x.label}</span>)}</nav>}
export function Badge({children,tone='gold'}:{children:ReactNode,tone?:'gold'|'success'|'danger'}){return <span className={'badge '+tone}>{children}</span>}
export function Skeleton(){return <div className="skeleton" aria-label="Memuat konten"><i/><i/><i/></div>}
export function EmptyState({icon,title,text}:{icon:ReactNode,title:string,text:string}){return <div className="empty">{icon}<h3>{title}</h3><p>{text}</p></div>}
export function Field({label,children,hint}:{label:string,children:ReactNode,hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function Modal({open,onClose,title,children}:{open:boolean,onClose:()=>void,title:string,children:ReactNode}){const id=useId();useEffect(()=>{if(!open)return;const f=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[open,onClose]);if(!open)return null;return <div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby={id}><button className="modal-close" onClick={onClose} aria-label="Tutup"><X/></button><h2 id={id}>{title}</h2>{children}</section></div>}
const menu=[['/','Beranda'],['/layanan','Layanan'],['/informasi','Informasi'],['/panduan','Panduan'],['/faq','FAQ'],['/kontak','Kontak']];
export function Navbar(){return <><div className="announcement">Layanan konsultasi daring membantu masyarakat memperoleh informasi tanpa harus datang terlebih dahulu ke kantor. <Link to="/panduan">Pelajari layanan</Link></div><header><Container className="navbar"><Logo/><div className="navlinks">{menu.map(([to,n])=><NavLink key={to} to={to} end={to==='/'}>{n}</NavLink>)}</div><div className="nav-actions"><Link to="/masuk" className="signin">Masuk</Link><Link to="/konsultasi" className="btn primary">Mulai Konsultasi <ArrowRight/></Link></div><MobileMenu menu={menu}/></Container></header></>}
function MobileMenu({menu}:{menu:string[][]}){let open=false;const toggle=(button:HTMLButtonElement)=>{open=!open;button.setAttribute('aria-expanded',String(open));document.querySelector('.mobile-drawer')?.classList.toggle('open',open)};return <><button className="menu" aria-expanded="false" aria-controls="mobile-nav" onClick={e=>toggle(e.currentTarget)}><Menu/></button><div className="mobile-drawer" id="mobile-nav">{menu.map(([to,n])=><NavLink key={to} to={to}>{n}</NavLink>)}<Link to="/masuk">Masuk</Link><Link to="/konsultasi" className="btn primary">Mulai Konsultasi</Link></div></>}
export function Footer(){return <footer><Container className="footer-inner"><div><Logo light/><p>Purwarupa layanan konsultasi Haji dan Umrah untuk mendukung akses informasi masyarakat Provinsi Riau.</p><Badge>Purwarupa · Bukan situs resmi</Badge></div><div><b>Layanan</b><Link to="/layanan">Daftar layanan</Link><Link to="/konsultasi">Buat konsultasi</Link><Link to="/panduan">Panduan</Link></div><div><b>Informasi</b><Link to="/informasi">Berita</Link><Link to="/faq">Pertanyaan umum</Link><Link to="/kontak">Kontak</Link></div><div><b>Informasi kantor</b><p>Provinsi Riau<br/>Detail alamat bersifat demonstrasi</p><p>Senin–Jumat · 08.00–16.00 WIB</p></div></Container><Container className="copyright"><span>© 2026 KEMENHAJ Riau · Purwarupa presentasi</span><span>Aksesibilitas · Privasi · Ketentuan</span></Container></footer>}
export function PublicLayout({children}:{children:ReactNode}){return <><Navbar/><main>{children}</main><Footer/></>}
export function PageHero({tag,title,description}:{tag:string,title:string,description:string}){return <section className="pagehero"><Badge>{tag}</Badge><h1>{title}</h1><p>{description}</p></section>}
