import{useState}from'react';import{NavLink,Link,useLocation}from'react-router-dom';import{Bell,ChevronDown,ChevronLeft,ChevronRight,Menu,Search,X}from'lucide-react';import type{ReactNode}from'react';import type{Consultation,NavItem,Status}from'../../data/dashboard';import{Logo,Modal}from'../ui';import{useDemo}from'../../hooks/useDemo';
export function DashboardShell({nav,role,children}:{nav:NavItem[];role:string;children:ReactNode}){const[open,setOpen]=useState(false);return <div className="dashboard-shell"><aside className={'dashboard-sidebar '+(open?'open':'')}><div className="side-brand"><Logo/><button onClick={()=>setOpen(false)} aria-label="Tutup menu"><X/></button></div><span className="role-label">{role} · Mode Demonstrasi</span><nav>{nav.map(x=><NavLink key={x.to} to={x.to} end={x.to.split('/').length===2}><x.icon/>{x.label}</NavLink>)}</nav><Link to="/" className="public-link">← Kembali ke situs publik</Link></aside><div className="dashboard-main"><DashboardHeader role={role} onMenu={()=>setOpen(true)}/>{children}</div></div>}
export function DashboardHeader({role,onMenu}:{role:string;onMenu:()=>void}){return <header className="dashboard-header"><button className="dashboard-menu" onClick={onMenu}><Menu/></button><div><b>{role}</b><small>Senin, 3 Agustus 2026 · Purwarupa</small></div><div className="header-actions"><button><Search/></button><button className="has-dot"><Bell/></button><span>AR</span></div></header>}
export function PageHeader({title,description,action}:{title:string;description:string;action?:ReactNode}){const heading=title==='Selamat datang, Nadia 👋'?'Selamat datang, Ahmad 👋':title;return <div className="page-header"><div><h1>{heading}</h1><p>{description}</p></div>{action}</div>}
export function StatisticCard({icon,value,label,change}:{icon:ReactNode;value:string;label:string;change?:string}){const presentationMetrics:Record<string,[string,string]>={'Konsultasi hari ini':['18','Konsultasi Hari Ini'],'Akan datang':['42','Terjadwal'],'Selesai bulan ini':['286','Selesai Bulan Ini'],'Saran kunjungan':['74','Rekomendasi Kunjungan Kantor'],'Rata-rata durasi':['27 menit','Rata-rata Durasi']};const shown=presentationMetrics[label]||[value,label];return <article className="statistic-card"><i>{icon}</i><div><strong>{shown[0]}</strong><span>{shown[1]}</span>{change&&<small>{change}</small>}</div></article>}
export function StatusBadge({status}:{status:string}){const{status:demoStatus}=useDemo();const shown=status==='Siap Bergabung'?demoStatus:status;const success=['Selesai','Aktif','Terbit','Sudah Dilihat','Siap Dibahas','Tepat Waktu','Lengkap'];const danger=['Dibatalkan','Tidak Aktif','Melewati Batas Waktu'];const warm=['Diajukan','Menunggu Jadwal','Belum Ditinjau','Draft','Mendekati Batas Waktu','Sebagian','Belum Lengkap','Menunggu Tindak Lanjut'];return <span className={'status-badge '+(success.includes(shown)?'success':danger.includes(shown)?'danger':warm.includes(shown)?'warm':'info')}>{shown}</span>}
export function SearchInput({value,onChange,placeholder='Cari...'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="dash-search"><Search/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
export function FilterBar({search,onSearch,children}:{search:string;onSearch:(v:string)=>void;children?:ReactNode}){return <div className="filter-bar"><SearchInput value={search} onChange={onSearch}/>{children}</div>}
export function ConsultationTable({rows,base}:{rows:Consultation[];base:string}){return <><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Referensi & peserta</th><th>Layanan & topik</th><th>Jadwal</th><th>Metode</th><th>Status</th><th/></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.reference}</b><small>{x.participant} · {x.city}</small></td><td><b>{x.service}</b><small>{x.topic}</small></td><td><b>{x.date}</b><small>{x.time} · {x.consultant}</small></td><td>{x.method}</td><td><StatusBadge status={x.status}/></td><td><Link to={`${base}/${x.id}`}>Detail →</Link></td></tr>)}</tbody></table></div><div className="mobile-consultations">{rows.map(x=><article><div><b>{x.reference}</b><StatusBadge status={x.status}/></div><h3>{x.service}</h3><p>{x.topic}</p><small>{x.date} · {x.time}</small><Link to={`${base}/${x.id}`}>Lihat detail →</Link></article>)}</div></>}
export function DataTable({headers,rows}:{headers:string[];rows:ReactNode[][]}){return <div className="data-table-wrap"><table className="data-table"><thead><tr>{headers.map(x=><th>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>}
export function Pagination(){return <div className="dash-pagination"><button><ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><button><ChevronRight/></button></div>}
export function Panel({title,action,children,className=''}:{title:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={'dashboard-panel '+className}><div className="dashboard-panel-head"><h2>{title}</h2>{action}</div>{children}</section>}
export function ActivityTimeline({items}:{items:{title:string;description:string;time:string}[]}){return <div className="activity-timeline">{items.map(x=><div><i/><span><b>{x.title}</b><p>{x.description}</p><small>{x.time}</small></span></div>)}</div>}
export function ScheduleCard({time,title,meta,status='Terjadwal'}:{time:string;title:string;meta:string;status?:string}){return <article className="schedule-card"><time>{time}</time><div><b>{title}</b><p>{meta}</p></div><StatusBadge status={status}/></article>}
export function DocumentCard({name,meta,note,status,actions}:{name:string;meta:string;note:string;status:string;actions?:ReactNode}){return <article className="document-card"><div className="file-icon">PDF</div><div><b>{name}</b><small>{meta}</small><p>{note}</p><StatusBadge status={status}/></div>{actions&&<div className="card-actions">{actions}</div>}</article>}
export function SimpleChart({values,labels}:{values:number[];labels?:string[]}){return <div className="simple-chart" aria-label="Grafik batang"><div>{values.map((v,i)=><i style={{height:`${v}%`}}><span>{labels?.[i]}</span></i>)}</div></div>}
export function Donut({value,label}:{value:number;label:string}){return <div className="donut" style={{background:`conic-gradient(var(--gold) ${value}%,#eee5d9 0)`}}><span><b>{value}%</b><small>{label}</small></span></div>}
export function DetailPanel({title,open,onClose,children}:{title:string;open:boolean;onClose:()=>void;children:ReactNode}){if(!open)return null;return <div className="detail-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="detail-panel"><button onClick={onClose}><X/></button><h2>{title}</h2>{children}</aside></div>}
export function ConfirmationDialog({open,title,text,onClose,onConfirm}:{open:boolean;title:string;text:string;onClose:()=>void;onConfirm:()=>void}){return <Modal open={open} onClose={onClose} title={title}><p>{text}</p><div className="dialog-actions"><button onClick={onClose}>Kembali</button><button className="danger" onClick={onConfirm}>Ya, lanjutkan</button></div></Modal>}
export function Select({label,options}:{label:string;options:string[]}){return <label className="dash-select"><span>{label}</span><select>{options.map(x=><option>{x}</option>)}</select><ChevronDown/></label>}
