import{BrowserRouter,Route,Routes}from'react-router-dom';import Home from'./pages/Home';import{ArticlePage,ContactPage,FAQPage,GuidePage,InformationPage,ServicesPage}from'./pages/PublicPages';import{ChooseService,Confirmation,ConsultationForm,Schedule}from'./pages/Consultation';import{LoginPage}from'./pages/AppPreviews';import MeetingDemo from'./pages/MeetingDemo';import{ConsultationProvider}from'./hooks/useConsultation';
import{UserConsultationDetail,UserConsultations,UserDocuments,UserNotifications,UserOverview,UserProfile,UserSchedule}from'./pages/dashboard/UserPages';
import{ConsultantConsultations,ConsultantDetail,ConsultantDocuments,ConsultantHistory,ConsultantOverview,ConsultantProfile,ConsultantSchedule}from'./pages/dashboard/ConsultantPages';
import{AdminActivity,AdminConsultants,AdminConsultations,AdminNews,AdminOverview,AdminReports,AdminSchedule,AdminServices,AdminSettings,AdminUsers}from'./pages/dashboard/AdminPages';
import{DemoProvider}from'./hooks/useDemo';import PresentationControl from'./components/PresentationControl';import NotFound from'./pages/NotFound';
import{CompletionDetail,CompletionEntry,CompletionRegister,DocumentationArchive,DocumentationDetail,EvidencePage,RequestDetail,RequestRegister,TimeMonitoring,TimeRecap}from'./pages/dashboard/LifecyclePages';
export default function App(){return <BrowserRouter><DemoProvider><ConsultationProvider><PresentationControl/><Routes>
 <Route path="/" element={<Home/>}/><Route path="/layanan" element={<ServicesPage/>}/><Route path="/konsultasi" element={<ChooseService/>}/><Route path="/konsultasi/form" element={<ConsultationForm/>}/><Route path="/konsultasi/jadwal" element={<Schedule/>}/><Route path="/konsultasi/konfirmasi" element={<Confirmation/>}/><Route path="/informasi" element={<InformationPage/>}/><Route path="/informasi/:slug" element={<ArticlePage/>}/><Route path="/panduan" element={<GuidePage/>}/><Route path="/faq" element={<FAQPage/>}/><Route path="/kontak" element={<ContactPage/>}/><Route path="/masuk" element={<LoginPage/>}/>
 <Route path="/dashboard" element={<UserOverview/>}/><Route path="/dashboard/konsultasi" element={<UserConsultations/>}/><Route path="/dashboard/konsultasi/:id" element={<UserConsultationDetail/>}/><Route path="/dashboard/jadwal" element={<UserSchedule/>}/><Route path="/dashboard/dokumen" element={<UserDocuments/>}/><Route path="/dashboard/notifikasi" element={<UserNotifications/>}/><Route path="/dashboard/profil" element={<UserProfile/>}/>
 <Route path="/dashboard/permohonan" element={<RequestRegister role="Pengguna"/>}/><Route path="/dashboard/permohonan/:id" element={<RequestDetail role="Pengguna"/>}/><Route path="/dashboard/bukti-pelayanan/:id" element={<EvidencePage/>}/><Route path="/dashboard/dokumentasi/:id" element={<DocumentationDetail role="Pengguna"/>}/>
 <Route path="/konsultan" element={<ConsultantOverview/>}/><Route path="/konsultan/jadwal" element={<ConsultantSchedule/>}/><Route path="/konsultan/konsultasi" element={<ConsultantConsultations/>}/><Route path="/konsultan/konsultasi/:id" element={<ConsultantDetail/>}/><Route path="/konsultan/dokumen" element={<ConsultantDocuments/>}/><Route path="/konsultan/riwayat" element={<ConsultantHistory/>}/><Route path="/konsultan/profil" element={<ConsultantProfile/>}/>
 <Route path="/konsultan/permohonan" element={<RequestRegister role="Konsultan"/>}/><Route path="/konsultan/permohonan/:id" element={<RequestDetail role="Konsultan"/>}/><Route path="/konsultan/penyelesaian" element={<CompletionRegister/>}/><Route path="/konsultan/penyelesaian/:id" element={<CompletionEntry/>}/><Route path="/konsultan/penyelesaian/detail/:id" element={<CompletionDetail/>}/><Route path="/konsultan/dokumentasi" element={<DocumentationArchive role="Konsultan"/>}/><Route path="/konsultan/dokumentasi/:id" element={<DocumentationDetail role="Konsultan"/>}/>
 <Route path="/admin" element={<AdminOverview/>}/><Route path="/admin/konsultasi" element={<AdminConsultations/>}/><Route path="/admin/konsultan" element={<AdminConsultants/>}/><Route path="/admin/pengguna" element={<AdminUsers/>}/><Route path="/admin/layanan" element={<AdminServices/>}/><Route path="/admin/jadwal" element={<AdminSchedule/>}/><Route path="/admin/informasi" element={<AdminNews/>}/><Route path="/admin/laporan" element={<AdminReports/>}/><Route path="/admin/aktivitas" element={<AdminActivity/>}/><Route path="/admin/pengaturan" element={<AdminSettings/>}/>
 <Route path="/admin/register-permohonan" element={<RequestRegister role="Administrator"/>}/><Route path="/admin/register-permohonan/:id" element={<RequestDetail role="Administrator"/>}/><Route path="/admin/register-penyelesaian" element={<CompletionRegister role="Administrator"/>}/><Route path="/admin/monitoring-waktu" element={<TimeMonitoring/>}/><Route path="/admin/rekap-waktu" element={<TimeRecap/>}/><Route path="/admin/dokumentasi" element={<DocumentationArchive role="Administrator"/>}/><Route path="/admin/dokumentasi/:id" element={<DocumentationDetail role="Administrator"/>}/>
 <Route path="/meeting/demo" element={<MeetingDemo/>}/><Route path="*" element={<NotFound/>}/>
</Routes></ConsultationProvider></DemoProvider></BrowserRouter>}
